# Generated by Django 4.2.3 on 2023-07-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cabin_Studio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('no_of_seats', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_charges', models.IntegerField(default=0)),
                ('security_amount', models.IntegerField(default=0)),
                ('Lock_in_duration', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('customer_Aadhaar', models.CharField(max_length=50)),
                ('Place_Allotted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cabin')),
                ('client_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.clientreq')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.clienttype')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.payment')),
            ],
        ),
    ]
