# Generated by Django 4.2.3 on 2023-07-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='client_req',
            new_name='client_Req',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='client_type',
            new_name='client_Type',
        ),
    ]
